//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agri_Energy_PROG7311_POE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enroll
    {
        public int EnrollmentId { get; set; }
        public string Name { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Information { get; set; }
        public string Contact { get; set; }
    }
}
