//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agri_Energy_PROG7311_POE
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenProduct
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double ProductPrice { get; set; }
        public int Quantity { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public string ProductImage { get; set; }
        public string ProductCategory { get; set; }
        public Nullable<int> FarmerId { get; set; }
    
        public virtual Farmer Farmer { get; set; }
    }
}
